# the input directory containing the unformatted posts
in: blog
# the output directory containing the formatted posts
out: dist
# the max amount of posts per page
max: 10
# where the github repo is
github: https://github.com/ResponsiveDev/blog/raw/master