# the input directory containing the unformatted posts
in: blog
# the output directory containing the formatted posts
out: dist
# the max amount of posts per page
max: 5
# where the github repo is
github: https://responsivedev.github.io/blog